/**
 * Type definitions for environment variables
 */
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV?: string;
      PORT?: string;
      APP_URL?: string;

      // Database
      DATABASE_URL?: string;
      DATABASE_HOST?: string;
      DATABASE_PORT?: string;
      DATABASE_NAME?: string;
      DATABASE_USER?: string;
      DATABASE_PASSWORD?: string;

      // JWT
      JWT_SECRET?: string;
      JWT_EXPIRATION?: string;
      JWT_ACCESS_TOKEN_SECRET?: string;
      JWT_REFRESH_TOKEN_SECRET?: string;
      JWT_ACCESS_TOKEN_EXPIRES_IN?: string;
      JWT_REFRESH_TOKEN_EXPIRES_IN?: string;
      JWT_ISSUER?: string;
      JWT_AUDIENCE?: string;

      // OAuth
      OAUTH_ACCESS_TOKEN_TTL?: string;
      OAUTH_REFRESH_TOKEN_TTL?: string;
      OAUTH_ID_TOKEN_TTL?: string;
      OAUTH_AUTHORIZATION_CODE_TTL?: string;
      OAUTH_JWT_ALGORITHM?: string;
      OAUTH_REQUIRE_PKCE?: string;
      OAUTH_ALLOW_IMPLICIT_FLOW?: string;
      OAUTH_ALLOW_CLIENT_CREDENTIALS_FLOW?: string;
      OAUTH_ALLOW_PASSWORD_FLOW?: string;
      OAUTH_ALLOW_REFRESH_TOKEN?: string;
      OAUTH_ROTATE_REFRESH_TOKEN?: string;
      OAUTH_ISSUER?: string;
      OAUTH_JWKS_URI?: string;
      OAUTH_AUTHORIZATION_ENDPOINT?: string;
      OAUTH_TOKEN_ENDPOINT?: string;
      OAUTH_USERINFO_ENDPOINT?: string;
      OAUTH_REVOCATION_ENDPOINT?: string;
      OAUTH_INTROSPECTION_ENDPOINT?: string;
      OAUTH_END_SESSION_ENDPOINT?: string;
      OAUTH_SUPPORTED_SCOPES?: string;
      OAUTH_DEFAULT_SCOPES?: string;
      OAUTH_SUPPORTED_PKCE_TRANSFORMATIONS?: string;
      OAUTH_REGISTRATION_ENDPOINT?: string;
      OAUTH_DYNAMIC_REGISTRATION?: string;
      OAUTH_ALLOWED_GRANT_TYPES?: string;
      OAUTH_ALLOWED_RESPONSE_TYPES?: string;
      OAUTH_ALLOWED_SCOPES?: string;
      OAUTH_JWT_ACCESS_TOKENS?: string;
      OAUTH_REFRESH_TOKEN_ROTATION?: string;

      // Passwordless
      PASSWORDLESS_WEBAUTHN_ENABLED?: string;
      PASSWORDLESS_WEBAUTHN_RP_NAME?: string;
      PASSWORDLESS_WEBAUTHN_RP_ID?: string;
      PASSWORDLESS_WEBAUTHN_ORIGIN?: string;
      PASSWORDLESS_WEBAUTHN_CHALLENGE_SIZE?: string;
      PASSWORDLESS_WEBAUTHN_TIMEOUT?: string;
      PASSWORDLESS_WEBAUTHN_ATTESTATION?: string;
      PASSWORDLESS_WEBAUTHN_AUTHENTICATOR_ATTACHMENT?: string;
      PASSWORDLESS_WEBAUTHN_USER_VERIFICATION?: string;
      PASSWORDLESS_WEBAUTHN_CREDENTIAL_TIMEOUT?: string;

      PASSWORDLESS_MAGIC_LINK_ENABLED?: string;
      PASSWORDLESS_MAGIC_LINK_TOKEN_LENGTH?: string;
      PASSWORDLESS_MAGIC_LINK_TOKEN_EXPIRATION?: string;
      PASSWORDLESS_MAGIC_LINK_DELIVERY_METHOD?: string;
      PASSWORDLESS_MAGIC_LINK_ALLOWED_DOMAINS?: string;
      PASSWORDLESS_MAGIC_LINK_MAX_TOKENS_PER_USER?: string;
      PASSWORDLESS_MAGIC_LINK_REUSE_WINDOW?: string;
      PASSWORDLESS_MAGIC_LINK_REQUIRE_VERIFIED_EMAIL?: string;

      PASSWORDLESS_EMAIL_OTP_ENABLED?: string;
      PASSWORDLESS_EMAIL_OTP_CODE_LENGTH?: string;
      PASSWORDLESS_EMAIL_OTP_CODE_EXPIRATION?: string;
      PASSWORDLESS_EMAIL_OTP_CODE_TYPE?: string;
      PASSWORDLESS_EMAIL_OTP_MAX_ATTEMPTS?: string;
      PASSWORDLESS_EMAIL_OTP_REQUIRE_VERIFIED_EMAIL?: string;
      PASSWORDLESS_EMAIL_OTP_RATE_LIMIT_WINDOW?: string;
      PASSWORDLESS_EMAIL_OTP_RATE_LIMIT_MAX?: string;

      PASSWORDLESS_SMS_OTP_ENABLED?: string;
      PASSWORDLESS_SMS_OTP_CODE_LENGTH?: string;
      PASSWORDLESS_SMS_OTP_CODE_EXPIRATION?: string;
      PASSWORDLESS_SMS_OTP_CODE_TYPE?: string;
      PASSWORDLESS_SMS_OTP_MAX_ATTEMPTS?: string;
      PASSWORDLESS_SMS_OTP_RATE_LIMIT_WINDOW?: string;
      PASSWORDLESS_SMS_OTP_RATE_LIMIT_MAX?: string;
      PASSWORDLESS_SMS_OTP_PROVIDERS?: string;

      PASSWORDLESS_CERTIFICATE_AUTH_ENABLED?: string;
      PASSWORDLESS_CERTIFICATE_AUTH_TRUSTED_CAS?: string;
      PASSWORDLESS_CERTIFICATE_AUTH_SUBJECT_DN_PATTERN?: string;
      PASSWORDLESS_CERTIFICATE_AUTH_ISSUER_DN_PATTERN?: string;
      PASSWORDLESS_CERTIFICATE_AUTH_VERIFY_REVOCATION?: string;
      PASSWORDLESS_CERTIFICATE_AUTH_ALLOW_SELF_SIGNED?: string;

      PASSWORDLESS_BIOMETRIC_ENABLED?: string;
      PASSWORDLESS_BIOMETRIC_REQUIRE_RESIDENT_KEY?: string;

      PASSWORDLESS_SESSION_COOKIE_NAME?: string;
      PASSWORDLESS_SESSION_COOKIE_MAX_AGE?: string;
      PASSWORDLESS_SESSION_COOKIE_SECURE?: string;
      PASSWORDLESS_SESSION_COOKIE_HTTP_ONLY?: string;
      PASSWORDLESS_SESSION_COOKIE_SAME_SITE?: string;
      PASSWORDLESS_SESSION_DURATION?: string;
    }
  }
}

export {};
